### ISSUE TITLE
License expression missing for NuGet package

### ISSUE THREAD

**Issue by lahma** [Taritsyn/AdvancedStringBuilder#1]
Currently there's no clear license expression for automatic tools to find for AdvancedStringBuilder:

![image](https://github.com/Taritsyn/AdvancedStringBuilder/assets/171892/59909f06-c908-448b-8cc2-cf54fa055ca7)

I'm not sure what would be the best course of action. I know you've put a lot of effort into this library, but would something like [ZString](https://www.nuget.org/packages/ZString) serve better as a dependency for consuming parties?

There's competition for string building and you have great expertise on other areas so might not be worth the effort to maintain? Sorry if I'm being a bit too blunt here.

**Comment by Taritsyn** [comment]
> Currently there's no clear license expression for automatic tools to find for AdvancedStringBuilder:

OK. When I have free time, I will definitely update this package. I think I have many more packages with this problem.

> …, but would something like [ZString](https://www.nuget.org/packages/ZString) serve better as a dependency for consuming parties?

To be honest, I am not familiar with this library. But the first thing I see is that it does not support old versions of .NET.

> There's competition for string building and you have great expertise on other areas so might not be worth the effort to maintain?

In fact, I want to move some of extension methods from the WebMarkupMin to the AdvancedStringBuilder. Almost all of my libraries use the AdvancedStringBuilder.

So, I went to bed 😴 Tomorrow I have to make edits to the JavaScript Engine Switcher's documentation 😉

**Comment by lahma** [comment]
One thing that also sprung to my mind is that as this is quite small utility, maybe it could be source-only package that would bring features as internal classes to consuming project? I'm just trying to minimize our dependency chain 😉

**Comment by Taritsyn** [comment]
You are not first person to offer me [such a solution](https://github.com/reactjs/React.NET/pull/644#issuecomment-450291424).

The fact is that this library is used at several levels of dependencies at once. And thus several libraries use one common pool.

In fact, StringBuilderPool should be part of .NET.

**Comment by lahma** [comment]
With Jint we just adopted the BCL's hidden [ValueStringBuilder](https://github.com/sebastienros/jint/blob/main/Jint/Pooling/ValueStringBuilder.cs), quite small and easy to have has internal thing in codebase.

**Comment by Taritsyn** [comment]
Before the AdvancedStringBuilder library appeared, source code of the StringBuilderPool was included in almost every library of mine.

First of all, it is an auxiliary library. I have never sought to promote the AdvancedStringBuilder. Actually, I have a lot of such libraries. For example, JavaScript Engine Switcher also be an auxiliary library until the [ReactJS.NET](https://github.com/reactjs/React.NET) appeared.

**Comment by lahma** [comment]
The license expression is showing correctly so closing this 👍🏻
